"""Test that shell completion scripts cover all registered CLI options.

Runs ``python -m calamus --help`` to obtain the definitive list of options —
this covers options registered via ``add_main_option``,
``add_main_option_entries``, and ``add_option_group`` without requiring any
static analysis of the source.  Every custom option must then appear in every
shell completion script.

When you add a new option in ``app.py``, this test will fail with a clear
message until you update:

    resources/completions/bash/calamus
    resources/completions/zsh/_calamus
    resources/completions/fish/calamus.fish
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).parent.parent

_COMPLETION_SCRIPTS = {
    "bash": _REPO_ROOT / "resources/completions/bash/calamus",
    "zsh": _REPO_ROOT / "resources/completions/zsh/_calamus",
    "fish": _REPO_ROOT / "resources/completions/fish/calamus.fish",
}

# Long option names generated by GLib itself — not ours to document.
_GLIB_BUILTINS = {"help", "help-all", "help-gapplication"}


def _registered_options() -> set[str]:
    """Return all custom long option names from ``calamus --help`` output."""
    result = subprocess.run(
        [sys.executable, "-m", "calamus", "--help"],
        capture_output=True,
        text=True,
        timeout=15,
    )
    names = {
        m.group(1)
        for m in re.finditer(r"--([a-z][a-z0-9-]+)", result.stdout)
        if m.group(1) not in _GLIB_BUILTINS
    }
    assert names, (
        "calamus --help produced no custom options. "
        "Verify the app is importable and add_main_option is called in __init__."
    )
    return names


def test_completion_scripts_cover_all_registered_options():
    """Every option from ``calamus --help`` must appear in all completion scripts."""
    option_names = _registered_options()

    for shell, path in _COMPLETION_SCRIPTS.items():
        content = path.read_text()
        for opt in sorted(option_names):
            # Fish uses `-l name` for long options; bash/zsh use `--name`.
            needle = f"-l {opt}" if shell == "fish" else f"--{opt}"
            assert needle in content, (
                f"Option '--{opt}' is not in the {shell} completion script "
                f"({path.relative_to(_REPO_ROOT)}). "
                f"Update resources/completions/ to fix this test."
            )
