# Pre-baked CI image for openSUSE Tumbleweed.
# Used by compat.yml (distro-matrix).
# Rebuilt only when this file or .github/workflows/ci-images.yml changes.
FROM opensuse/tumbleweed

RUN zypper --non-interactive refresh && \
    zypper --non-interactive install \
    bash gcc gcc-c++ \
    python3 python3-gobject python3-cairo \
    typelib-1_0-Gtk-4_0 typelib-1_0-Adw-1 typelib-1_0-GtkSource-5 \
    libgtk-4-1 libadwaita-1-0 \
    xvfb-run dbus-1 curl git \
    cairo-devel gobject-introspection-devel python3-devel pkg-config && \
    ln -sf /usr/bin/gcc /usr/bin/cc && \
    zypper clean --all

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"
